# Generated by Django 5.2.17 on 2026-08-07 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='es_fiado',
            field=models.BooleanField(default=False, verbose_name='Venta a crédito (fiado)'),
        ),
        migrations.AddField(
            model_name='venta',
            name='monto_adeudado',
            field=models.PositiveIntegerField(default=0, verbose_name='Monto adeudado'),
        ),
        migrations.AddField(
            model_name='venta',
            name='nombre_cliente_fiado',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nombre del cliente (fiado)'),
        ),
        migrations.AddField(
            model_name='venta',
            name='tipo_entrega',
            field=models.CharField(choices=[('domicilio', 'Domicilio'), ('tienda', 'Comprado en Tienda')], default='tienda', max_length=20, verbose_name='Tipo de entrega'),
        ),
    ]
